# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t8KhMmfM9Cz9G0H8S4l3XWsYUQyQFtX
"""

# =================================================================
# TRABAJO FINAL: FUNDAMENTOS DE PROGRAMACIÓN
# ESTRUCTURA DE DATOS: MATRICES Y MODULARIDAD
# =================================================================

# MÓDULO 1: Función para calcular el precio final de un producto
def calcular_precio_final(producto, categoria_objetivo, precio_umbral):
    """
    Esta función recibe un producto (una fila de la matriz) y evalúa
    si cumple las condiciones para aplicar el 15% de descuento.
    """
    # Desempaquetamos los datos del producto para entenderlos mejor
    nombre = producto[0]
    categoria = producto[1]
    precio_base = producto[2]

    # Lógica de negocio: Verificar ambas condiciones
    if categoria == categoria_objetivo and precio_base > precio_umbral:
        # Si cumple, aplicamos el 15% de descuento
        descuento = precio_base * 0.15
        precio_final = precio_base - descuento
    else:
        # Si no cumple, el precio se queda exactamente igual
        precio_final = precio_base

    return precio_final


# MÓDULO PRINCIPAL: Controla la ejecución del programa
def programa_principal():
    # 1. Creamos la matriz del menú con 6 productos
    # Formato de cada fila: [Nombre, Categoría, Precio Base]
    menu_restaurante = [
        ["Bandeja Paisa", "Plato Fuerte", 32000],
        ["Ajiaco Santaferereño", "Plato Fuerte", 24000],
        ["Hamburguesa Artesanal", "Comida Rápida", 26000],
        ["Empanada de Carne", "Entrada", 4000],
        ["Limonada Cerezada", "Bebida", 9000],
        ["Flan de Caramelo", "Postre", 12000]
    ]

    # 2. Definimos los parámetros de la promoción
    categoria_promo = "Plato Fuerte"
    umbral_precio_promo = 25000

    # Imprimimos un encabezado bonito para la entrega
    print("==========================================================")
    print("          INFORME DE GESTIÓN DE PRECIOS - MENÚ           ")
    print(f" Promoción para: {categoria_promo} con precio mayor a ${umbral_precio_promo}")
    print("==========================================================")

    # 3. Recorremos la matriz producto por producto usando un ciclo for
    for producto in menu_restaurante:
        nombre_prod = producto[0]
        categoria_prod = producto[1]
        precio_base_prod = producto[2]

        # Llamamos al módulo de cálculo para obtener el precio final
        precio_final_prod = calcular_precio_final(producto, categoria_promo, umbral_precio_promo)

        # Revisamos si el precio cambió para avisarle al usuario si tuvo promo
        if precio_final_prod < precio_base_prod:
            estado_promo = "(¡Promoción Aplicada!)"
        else:
            estado_promo = "(Precio Regular)"

        # 4. Salida: Mostramos los resultados en pantalla de forma ordenada
        print(f"Producto: {nombre_prod}")
        print(f"  - Categoría: {categoria_prod}")
        print(f"  - Precio Base: ${precio_base_prod:,}")
        print(f"  - Precio Final: ${precio_final_prod:,} {estado_promo}")
        print("-" * 58)

# Ejecutamos el programa
programa_principal()